package com.basics.threads;

public class ResultTask extends Thread{
    @Override
    public void run(){
        System.out.println("result generated by:"+ Thread.currentThread().getState());
    }

    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();
        t1.start();
    }
}
/*
ℹ️Points to remeber :
⭐start () Multithreading - Multitasking - concurrency
⭐ run() Normal Execution
⭐start() Tnternally  calls run()
⭐thread cannot be started twice
 */